name: Lighthouse CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse tools
        run: npm install -g @lhci/cli lighthouse-badges

      - name: Run Lighthouse CI
        run: lhci autorun

      - name: Generate badges
        run: |
          npx lighthouse-badges --url https://ryan-2025.vercel.app --output-path badges

      - name: Commit and push badges
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add badges/*.svg
          git commit -m "chore: update Lighthouse badges" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
